### ISSUE TITLE
Страница переведена не корректно

### ISSUE THREAD

**Issue by Amangeldi** [dotnet/AspNetCore.Docs.ru-ru#102]
[Введите отзыв здесь]
Скорее всего был использован машинный перевод, но страница переведена некорректно https://docs.microsoft.com/ru-ru/aspnet/core/security/authorization/simple?view=aspnetcore-3.1

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Простая Авторизация в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/security/authorization/simple?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Amangeldi** [comment]
![image](https://user-images.githubusercontent.com/10187185/98352600-0ba09080-2040-11eb-8190-6ef39feec1c2.png)

**Comment by Rick-Anderson** [comment]
[Enter your review here]
Most likely machine translation was used, but the page was not translated correctly https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1

The doc has `:::no-loc(Razor):::`, that looks like a bug in the MT. I've seen this is other docs. @JasonCard  please review.

**Comment by Rick-Anderson** [comment]
@JasonCard  312 results

https://docs.microsoft.com/ru-ru/search/?scope=ASP.NET%20Core&view=aspnetcore-3.1&terms=%3A%3A%3Ano-loc&category=Documentation

**Comment by JasonCard** [comment]
It seems that bug fix deployed for the no-loc feature introduced this new bug and all terms listed in no-loc metadata are currently getting displayed like ":::no-loc(SignalR):::". We're currently checking with our engineering team if the previous fix can be rolled back or the new bug can be quickly fixed.
 
@Rick-Anderson Thank you for the search results and I've pass it on to our engineering team.

**Comment by Rick-Anderson** [comment]
It's just an annoying bug and doesn't prevent customers from reading the doc. Hopefully next time they can test before rolling out  :smile:

**Comment by JasonCard** [comment]
@Amangeldi Thank you again for reporting this issue and it's now fixed.
cc @Rick-Anderson
