### ISSUE TITLE
Error on page

### ISSUE THREAD

**Issue by faketogosamogo** [dotnet/AspNetCore.Docs.ru-ru#107]
Authorization in ASP.NET Core is controlled with AuthorizeAttribute and its various parameters. In its simplest form, applying the [Authorize] attribute to a controller, action, or Razor Page, limits access to that component to any authenticated user.

For example, the following code limits access to the AccountController to -any- [not] authenticated user. //lost not

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Простая Авторизация в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/security/authorization/simple?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The statement is correct. 
Please close.
