### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by alinagai** [dotnet/AspNetCore.Docs.ru-ru#114]
[Введите отзыв здесь]
Вопрос: как адаптировать создание связанных таблиц для работы на Mac (с SQllite)/ Команды altercolumn и тд,а также  командные строки sql не проходят

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Учебник. Использование ASP.NET MVC с EF Core. Чтение связанных данных](https://docs.microsoft.com/ru-ru/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Question: How to adapt the creation of linked tables to work on Mac (with SQllite) / Commands altercolumn and so on, as well as command lines sql do not pass

That's beyond the scope of this tutorial.
