### ISSUE TITLE
Ошибка в коде примера

### ISSUE THREAD

**Issue by Maximys** [dotnet/AspNetCore.Docs.ru-ru#79]
Метод Update(string id, Book bookIn) содержит ошибку - мы в bookIn не заполняем свойство Id, в связи с чем ReplaceOne вернет исключение. Должно быть как-то так:
public async void Update(string id, Book bookIn)
        {
            bookIn.Id = id;//фикс ошибки.
            await Books.ReplaceOneAsync(b =&gt; b.Id == id, bookIn);
        }

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Создание веб-API с помощью ASP.NET Core и MongoDB](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @Maximys
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17692](https://github.com/dotnet/AspNetCore.Docs/issues/17692) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Здравствуйте, @Maximys!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/dotnet/AspNetCore.Docs/issues/17692.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
