### ISSUE TITLE
Wrong translation to RU. No capital letter at the beginning of the sentence.

### ISSUE THREAD

**Issue by AlexanderPodlesniyQs** [dotnet/AspNetCore.Docs.ru-ru#81]
A 200 status code is returned with the Product object when the product does exist. The Ok convenience method is invoked as shorthand for return new OkObjectResult(product);
Код состояния 200 возвращается с объектом Product, если продукт не существует. вызывается удобный метод Ok в качестве сокращения return new OkObjectResult(product).

This part:
"when the product does exist" -&gt; "если продукт не существует". Correct translation: "если продукт существует"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Типы возвращаемых значений действий контроллера в веб-API ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @AlexanderPodlesniyQs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @AlexanderPodlesniyQs 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
