### ISSUE TITLE
Newtonsoftjson

### ISSUE THREAD

**Issue by MikeBorovik** [dotnet/AspNetCore.Docs.ru-ru#85]
в переводе на рускую локаль, название nuget пакета частично затронуто переводом:
Microsoft. AspNetCore. MVC. невтонсофтжсон 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Форматирование данных отклика в веб-API ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @MikeBorovik
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Здравствуйте, @MikeBorovik .

Спасибо за Ваше предложение!

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются.

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода.

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым.

Большое спасибо за поддержку!

Microsoft DOCS Global Experience Team

cc @JasonCard

**Comment by JasonCard** [comment]
Hi @MikeBorovik 
Thank you for your feedback.
I've opened this PR [#18369](https://github.com/dotnet/AspNetCore.Docs/pull/18369) in English content to prevent this over-localization issue.

Best regards,
Jason
