### ISSUE TITLE
Поломанные ссылки в меню

### ISSUE THREAD

**Issue by Ogrvat** [dotnet/AspNetCore.Docs.ru-ru#86]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [Основы ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ogrvat** [comment]
![Скриншот 05-06-2020 145727](https://user-images.githubusercontent.com/30263721/83873689-eaf4a780-a73c-11ea-9489-197ddec30c3a.jpg)
![Скриншот 05-06-2020 145719](https://user-images.githubusercontent.com/30263721/83873691-ec25d480-a73c-11ea-993f-241a0c59f018.jpg)

**Comment by srvbpigh** [comment]
Hello, @Ogrvat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @Ogrvat
Спасибо за отзыв.  

Наши инженеры рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
